config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  devise_for :users
  resources :books
  resources :homes
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
	validates :title, length: {minimum: 1}
	validates :title, length: {maximum: 200}
	validates :body, presence: true
	validates :body, length: {minimum: 1}
	validates :body, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  validates :name, presence: true
  validates :name, length: {minimum: 2}
  validates :name, length: {maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: {maximum: 50}
  has_many :books, dependent: :destroy
  attachment :profile_image
  # has_many :users, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
    user_path(resource)
 end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
		@users = User.all
		
  end

  def show
    @book = Book.new
		@bookdetail = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
			redirect_to books_path
    end
  end  
  
  
  
  def create
    @book = Book.new(book_params)
    # binding.pry
    
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = "You have creatad book successfully."
    redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end




  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end



  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

private

def book_params
  params.require(:book).permit(:title, :body)
end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
		@book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
			redirect_to user_path(@current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    # binding.pry
		if @user.update(user_params)
			flash[:success] = "You have updated user successfully."
			redirect_to user_path(@user.id)
		else
			render :action => "edit"
		end
    
  end

  private

def user_params
  params.require(:user).permit(:name, :profile_image, :introduction)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <h2>Editing Book</h2>
      <%= form_for(@book) do |f| %>
      <label>Title</label>
        <br>
        <%= f.text_field :title %>
        <br>
      <label>opinion</label>
        <br>
        <%= f.text_area :body %>
        <br>
        <br>
        <br>
        <div class="actions">
          <%= f.submit 'Update Book', class: "btn-sm btn-success" %>
          </div>
          <br>
            <td><%= link_to "Show", book_path %></td>
            <td>|</td>
            <td><%= link_to "Back", books_path %></td>
          <% end %>
      </div>
      
          <p style="padding-left:500px;">CopyRight Infratop.inc</p>
      </div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
	<div class="row">
		<div class="col-md-3">
			<%= render 'partial template/list', book: @book, user: @user %>
		</div>
   
    <div class="col-md-8 offset-md-1">
    	<h2>Books</h2>
    	<table class="table">
    		<thead>
    			<tr>
    				<th></th>
    				<th>Title</th>
    				<th>Opinion</th>
    				<th colspan="3"></th>
		      </tr>
		      </thead>
		      <tbody>
		      	<% @books.reverse_each do |book| %>
						<tr>

							<td><%= link_to user_path(book.user) do %>
							<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg" %>
							<% end %>
							</td>

				     	<td><%= link_to book.title, book_path(book.id) %></td>
			      	<td><%= book.body %></td>
				   	</tr>
		       	<% end %>
		    	</tbody>
		     	</table>
		     	</div>
		</div>
		  <p style="padding-left:500px;">CopyRight Infratop.inc</p>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h1>hoge</h1>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3">
		<%= render 'partial template/list', book: @book, user: @bookdetail.user %>
		</div>
		<div class="col-md-9">
		<div class="col-md-8 offset-md-1">
		<h2>Book detail</h2>
		<table class="table">
			<thead>
				<tr align="center">
					<th></th>
		      <th></th>
		   		<th></th>
	     		<th></th>
	     		<th colspan="3"></th>
		     </tr>
		     </thead>
		     <tbody>

		     	<td><%= attachment_image_tag @user, :profile_image, format:'jpeg', fallback: "no_image.jpg", size: "50x50" %><br>
		     	<%= link_to @bookdetail.user.name, user_path(@bookdetail.user.id) %></td>
		     		<td><%= link_to @bookdetail.title, book_path(@bookdetail.id) %></td>
		     		<td><%= @bookdetail.body %></td>
		     		<% if @bookdetail.user_id == current_user.id %>
		     		<th><%= link_to "Edit", edit_book_path(@bookdetail.id), class: "btn-sm btn-success edit_book_#{@bookdetail.id}" %></th>
		     		<th><%= link_to "Destroy", book_path(@bookdetail.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger destroy_book_#{@bookdetail.id}" %></th>
		     		<% end %>
				  </tr>
		   	</tbody>
		 </table>
		 </di>
		</div>
		
			<p style="padding-left:500px;">CopyRight Infratop.inc</p>
		</div>
  	</div>
</div>

app/views/homes/about.html.erb
<div class="container">
	<h1 class="text-center">welcome to <i class="fas fa-book"></i>Bookers  !!</h1>
	</div>
	<br>
	<br>
	<p class="text-center">CopyRight Infratop.inc</p>
	</div>
</div>

app/views/homes/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-6 col-md-12">
		<h1 align="center">welcome to <i class="fas fa-book"></i></i>Bookers   !!</h1>
		<p align="center">In<i class="fas fa-book"></i>Bookers,</p>
		<p align="center">you can share and exchange your options,inpressiond,and emotions</p>
		<p align="center">about varioius books!</p>
		<div align="center">
		<%= link_to "Log in",new_user_session_path ,class: "btn btn-info col-lg-3 col-xs-offset-1 sign_in" %>
		<br>
		<br>
		<%= link_to "Sign up",new_user_registration_path ,class: "btn btn-success col-lg-3 col-xs-offset-1 sign_up" %>
		</div>
		</div>
	
    </div>
	</div>
<br>
  <p class="text-center">CopyRight Infratop.inc</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title>BookersVer2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/340021f413.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


 <body>
     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
         <a class="navbar-brand" href="/">Bookers</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
     </button>

 <div class="collapse navbar-collapse" id="navbarNavDropdown">
      

    

          <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>


    
  
             <li>
                <%= link_to user_path(current_user.id) do %>
                <p class="" style="color: white;"><i class="fas fa-home">Home</i></p>
                <% end %>
              </li>             

              <li>
                   <a class="fas fa-users nav-link text-light" href="/users">Users</a>
              </li>

              <li>
                  <a class="fas fa-book-open nav-link text-light" href="/books">Books</a>
              </li>

              <li>
                   <a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">logout</a>
              </li>




                <% else %>


         <li>
               <a class="fas fa-home nav-link text-light" href="/">Home</a>
            </li>


            <li>
                <a class="fas fa-link nav-link text-light" href="/home/about">About</a>
            </li>
            
            <li>
                <a class="fas fa-user-plus nav-link text-light" href="/users/sign_up">sign up</a>
            </li>

            <li>
                <a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in">login</a>
            </li>



                <% end %>
                </ul>
                
           
        </div>
      </nav>
      </header>


    <div class="container">
        <div class="row">
            <div class="alert-info">
                <% flash.each do |key, value| %>
                <%= content_tag(:div, value, class: "#{key}") %>
                <% end %>
            </div>
        </div>
    </div>



    <%= yield %>

      <p class="no-margin" style="font-size: 11px;">
      <br>
      </p>

  </body>


</html>

app/views/partial template/_list.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div>
    <h1>User info</h1>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>

    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <td><%= user.name %></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><%= user.introduction %></td>
          </tr>
          </tbody>
    </table>
    <P class="text-center" style="border-style: groove;"><%= link_to "", edit_user_path(user),  class: "col-xs-12 btn btn-default fas fa-user-cog" %></P>


    <h2>New book</h2>
    <%= form_for(book) do |f| %>
    <label>Title</label>
    <br>
    <%= f.text_field :title %>
    <br>
    <label>opinion</label>
    <br>
    <%= f.text_area :body %>
      <br>
      <br>
      <br>
      <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
      <% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
  <% if @user.errors.any? %>
  <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= form_for(@user) do |f| %>
      <label>Name</label>
    <br>
      <%= f.text_field :name, class: "name" %>
      <br>
      <br>
      <label>Image</label>
      <br>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-image" %>
      <br>
      <br>
      <label>Introduction</label>
      <br>
      <%= f.text_area :introduction, class: "introduction" %>
      <br>
      <br>
      <br>
      <%= f.submit "Update User", class: "btn btn-secondary" %>
        <p style="text-center">CopyRight Infratop.inc</p>
      <% end %>
    </div>
    <div class="col-xs-3 col-xs-offset-9">
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container" px-5 px-sm-0>
	<div class="row">
		<div class="col-md-3">
			<%= render 'partial template/list', book: @book, user: @user %>
		</div>
		<div class="col-lg-9">
	<table class="table">
		<h2>Users</h2>
	<thead>
	<tr>
		<th>image</th>
 		<th>name</th>
 		<th></th>

 		</tr>
	</thead>
	<tbody>
		<% @users.reverse_each do |user| %>
		<tr>

			<td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %></td>
			<td><%= user.name %></td>
			<td><%= link_to 'Show', user_path(user.id) %></td>
		</tr>
		<% end %>
	</tbody>
		     	</table>
		</div>
		<div class="col-md-8 offset-md-1">
		      <p style="padding-left:500px;">CopyRight Infratop.inc</p>
		</div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
	<div class="row">
		<div class="col-md-3">
			<%= render 'partial template/list', book: @book, user: @user %>
		</div>
		
		<div class="col-md-8 offset-md-1">
			
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr align="center">
					<th></th>
		      <th>Title</th>
		      <th>Opinion</th>
		      <th colspan="3"></th>
		     </tr>
		  </thead>
		  <tbody>
		  	<% @books.reverse_each do |book| %>
		  	
		  	<td><%= link_to image_tag("no_image.jpg", class: "book_#{@book.id}") %></td>
		  	
		  	
				<td><%= link_to book.title, book, class: "book_#{@book.id}" %></td>
				<td><%= book.body %></td>
				</tr>
		    <% end %>
		   </tbody>
		  </table>
		</div>
		</div>
		<div class="col-xs-3 col-xs-offset-9">
		      <p style="padding-left:500px;">CopyRight Infratop.inc</p>
		</div>
  </div>
</div>